#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jul 29 12:52:58 2018
Numerical Analysis HW5 Q1
@author: yuzhezhou
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import spline

t1  = np.arange(0.9,4.2,0.1)
q   = -11 + 55/3*t1 - 17/2*t1**2 + 7/6*t1**3
q1  = np.zeros(len(t1))

#c = [0.05,0.1,0.03]
c   = 0.3

for i in range(0,len(t1)):
    q1[i] = q[i]*(1+c*np.random.rand())

t        = np.linspace(0.5,4.5,num=1000)
s        = spline(t1,q1,t)
p        = np.polyfit(t1,q1,32)
p1       = np.polyfit(t1,q1,3)

q2       = np.polyval(p1,t1)

max_diff = np.max(np.abs(q1-q2))

plt.figure(0)
plt.plot(t,s)
plt.plot(t,np.polyval(p,t))
plt.plot(t,np.polyval(p1,t))
plt.plot(t1,q1,'o')
plt.ylim((-5, 5)) 
plt.legend(('spline','32 deg','cubic'))